version: '3'

services:
  sandbox:
    image: 'enqueue/dev:latest'
    entrypoint: '/entrypoint.sh'
    working_dir: '/mqs/symfony'
    restart: 'always'
    depends_on:
      - rabbitmq
    volumes:
      - ./docker/container/php/cli.ini:/etc/php/7.1/cli/conf.d/1-sandbox_cli.ini
      - ./docker/container/entrypoint.sh:/entrypoint.sh
      - ./docker/shared/:/shared
      - ./:/mqs
    env_file: 'symfony/app/config/.env'
    environment:
      - HISTFILE=/shared/.bash_history
    ports:
      - "80:80"

  rabbitmq:
    build: { context: ., dockerfile: Dockerfile.rabbitmq }
    restart: 'always'
    ports:
      - "15673:15672"
      - "15674:15674"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=mqs
